// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Z0BV6uOiJhTM_sLGoY1EEsaItCDtPZs',
    appId: '1:1059019581658:web:880db94b4cb6940a809de3',
    messagingSenderId: '1059019581658',
    projectId: 'video-stream-643e8',
    authDomain: 'video-stream-643e8.firebaseapp.com',
    storageBucket: 'video-stream-643e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP4prx41vP4pfYp4UcmsUn__tNt2IA4Sg',
    appId: '1:1059019581658:android:175c660349837689809de3',
    messagingSenderId: '1059019581658',
    projectId: 'video-stream-643e8',
    storageBucket: 'video-stream-643e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHfteWnEvb-9CXnYPby_XWWRArKU69V9A',
    appId: '1:1059019581658:ios:0ac015df462b606e809de3',
    messagingSenderId: '1059019581658',
    projectId: 'video-stream-643e8',
    storageBucket: 'video-stream-643e8.firebasestorage.app',
    iosBundleId: 'com.example.videoStreamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHfteWnEvb-9CXnYPby_XWWRArKU69V9A',
    appId: '1:1059019581658:ios:0ac015df462b606e809de3',
    messagingSenderId: '1059019581658',
    projectId: 'video-stream-643e8',
    storageBucket: 'video-stream-643e8.firebasestorage.app',
    iosBundleId: 'com.example.videoStreamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_Z0BV6uOiJhTM_sLGoY1EEsaItCDtPZs',
    appId: '1:1059019581658:web:dd7a7caaf6139d8a809de3',
    messagingSenderId: '1059019581658',
    projectId: 'video-stream-643e8',
    authDomain: 'video-stream-643e8.firebaseapp.com',
    storageBucket: 'video-stream-643e8.firebasestorage.app',
  );
}
